version: '3.8'

services:
  translation-service:
    build: .
    container_name: translation-service
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MODEL_NAME=facebook/nllb-200-distilled-600M
      - CACHE_TTL=2592000  # 30 days
      - TRANSFORMERS_CACHE=/app/models
      - HF_HOME=/app/models
    volumes:
      # Persist model cache to avoid re-downloading
      - model-cache:/app/models
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: translation-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

volumes:
  model-cache:
    driver: local
  redis-data:
    driver: local